name: careless
on:
  push:

jobs:
  careless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gfm_version:
        - hello"; touch /tmp/flag; echo "
        - world

    steps:
      - name: Look
        run: ls /tmp

      - name: Run a one-line script (safely)
        env:
          gfm_version: ${{ matrix.gfm_version }}
        run: echo "something $gfm_version else"

      - name: Look
        run: ls /tmp

      - name: Run a one-line script (safely)
        run: echo "something ${{ matrix.gfm_version }} else"

      - name: Look
        run: ls /tmp

